import React from "react"
import { graphql, useStaticQuery } from "gatsby"
import { getImage, GatsbyImage } from "gatsby-plugin-image"
import { Container, Row, Col } from "react-bootstrap"
import { convertToBgImage } from "gbimage-bridge"
import BackgroundImage from "gatsby-background-image"
import { StaticImage } from "gatsby-plugin-image"

export default function ClimateActionBanner({ className }) {
  const { mobileImage, desktopImage } = useStaticQuery(
    graphql`
      query {
        mobileImage: file(relativePath: { eq: "white.jpg" }) {
          childImageSharp {
            fluid(maxWidth: 490, quality: 100) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
        desktopImage: file(relativePath: { eq: "cliamet-sec.jpg" }) {
          childImageSharp {
            fluid(quality: 100, maxWidth: 4160) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    `
  )

  const sources = [
    mobileImage.childImageSharp.fluid,
    {
      ...desktopImage.childImageSharp.fluid,
      media: `(min-width: 491px)`,
    },
  ]

  return (
    <BackgroundImage
      Tag={`section`}
      id={`media-test`}
      // className={className}
      className="crestbanner"
      fluid={sources}
    >
      <div className="crest-banner-home climate-banner">
        <Container>
          <div className="climate-sec-inner">
            <div className="climate-box-inner">
              <h6>INDRODUCING</h6>
              <h2>CLIMATE HUBS</h2>

              <p>
                Buildings consume 40% of energy worldwide as 21% of the
                greenhouse gases originate from them. This is the time to
                rethink the way communities are built. <br></br>
                Climate hub is “the solution” in the current scenario. Climate
                hubs are closed ecological systems which do not rely on matter
                exchange with anything from outside of the system. The waste
                generated by one species is used by another species forming
                closely knit biological communities within themselves. <br></br>
                New ecosystems are created by making the place conducive for
                various organisms thereby increasing the biodiversity of the
                place. Homes that are built and integrated with nature enhance
                the quality of bionetworks such as soil, air and water including
                the surrounding neighborhoods & environment.
              </p>
            </div>
            <div className="climate-box-books">
              <Row className="climate-inner-row">
                <Col className="climate-box-img col-lg-3 col-12">
                  <StaticImage src="../images/climate-books.jpg" />
                </Col>
                <Col className="box-right-con ">
                  <h2 className="mission-subheading heading-color">
                    Backcreek, Monroe County, West Virginia.
                  </h2>
                  <p className="mission-sub-text">
                    A consolidation of gross study with focus on the current
                    situation due to several man-made developments across Monroe
                    County boiling down to Back Creek. This includes mapping of
                    climatic and geological changes that occurred over a period
                    and its impact on natural resources.
                  </p>
                  <p className="read-text">
                    <a href="/CAR-BackCreek/" className="readmore">
                      Read More <StaticImage src="../images/right-arrow.png" />
                    </a>
                  </p>
                </Col>
              </Row>
              <Row className="climate-inner-row">
                <Col className="climate-box-img col-lg-3 col-12">
                  <StaticImage src="../images/NEOM 01-02-22.jpg" />
                </Col>
                <Col className="box-right-con">
                  <h2 className="mission-subheading heading-color">
                    Neom, Saudi Arabia.
                  </h2>
                  <p className="mission-sub-text">
                    Primary focus of this report is to constitute a solution
                    framework and restore ecological balance with a broad
                    roadmap towards environmental impact goals of CREST
                    Foundation overlapped and measured in comparison with UN
                    Sustainable Development Goals defined for Saudi Arabia.
                  </p>
                  <p className="read-text">
                    <a href="/CAR-Neom/" className="readmore">
                      Read More
                      <StaticImage src="../images/right-arrow.png" />
                    </a>
                  </p>
                </Col>
              </Row>
              <Row className="climate-inner-row">
                <Col className="climate-box-img col-lg-3 col-12">
                  <StaticImage src="../images/Dhriti_Climate Hub_cover.jpg" />
                </Col>
                <Col className="box-right-con">
                  <h2 className="mission-subheading heading-color">
                    Zaheerabad, Hyderabad
                  </h2>
                  <p className="mission-sub-text">
                    A study of the existing bionetwork in and around Zahirabad,
                    Telangana along with understanding the surrounding
                    ecosystems and analyzing how this affects the living
                    conditions of humans, Flora, and Fauna throughout the
                    district.
                  </p>
                  <p className="read-text">
                    <a href="/CAR-Zaheerabad/" className="readmore">
                      Read More
                      <StaticImage src="../images/right-arrow.png" />
                    </a>
                  </p>
                </Col>
              </Row>
            </div>
          </div>
        </Container>
      </div>
    </BackgroundImage>
  )
}
